# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anomaly_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anomaly_detection.proto',
  package='twitteranomalydetection',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61nomaly_detection.proto\x12\x17twitteranomalydetection\"B\n\x07Request\x12\x10\n\x08raw_json\x18\x01 \x01(\t\x12\x11\n\tonly_last\x18\x02 \x01(\t\x12\x12\n\nresampling\x18\x03 \x01(\x08\"y\n\nDictionary\x12=\n\x05pairs\x18\x01 \x03(\x0b\x32..twitteranomalydetection.Dictionary.PairsEntry\x1a,\n\nPairsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x32u\n\x17TwitterAnomalyDetection\x12Z\n\x0f\x44\x65tectAnomalies\x12 .twitteranomalydetection.Request\x1a#.twitteranomalydetection.Dictionary\"\x00\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='twitteranomalydetection.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_json', full_name='twitteranomalydetection.Request.raw_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='only_last', full_name='twitteranomalydetection.Request.only_last', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resampling', full_name='twitteranomalydetection.Request.resampling', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=118,
)


_DICTIONARY_PAIRSENTRY = _descriptor.Descriptor(
  name='PairsEntry',
  full_name='twitteranomalydetection.Dictionary.PairsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='twitteranomalydetection.Dictionary.PairsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='twitteranomalydetection.Dictionary.PairsEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=241,
)

_DICTIONARY = _descriptor.Descriptor(
  name='Dictionary',
  full_name='twitteranomalydetection.Dictionary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pairs', full_name='twitteranomalydetection.Dictionary.pairs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_DICTIONARY_PAIRSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=241,
)

_DICTIONARY_PAIRSENTRY.containing_type = _DICTIONARY
_DICTIONARY.fields_by_name['pairs'].message_type = _DICTIONARY_PAIRSENTRY
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Dictionary'] = _DICTIONARY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'anomaly_detection_pb2'
  # @@protoc_insertion_point(class_scope:twitteranomalydetection.Request)
  })
_sym_db.RegisterMessage(Request)

Dictionary = _reflection.GeneratedProtocolMessageType('Dictionary', (_message.Message,), {

  'PairsEntry' : _reflection.GeneratedProtocolMessageType('PairsEntry', (_message.Message,), {
    'DESCRIPTOR' : _DICTIONARY_PAIRSENTRY,
    '__module__' : 'anomaly_detection_pb2'
    # @@protoc_insertion_point(class_scope:twitteranomalydetection.Dictionary.PairsEntry)
    })
  ,
  'DESCRIPTOR' : _DICTIONARY,
  '__module__' : 'anomaly_detection_pb2'
  # @@protoc_insertion_point(class_scope:twitteranomalydetection.Dictionary)
  })
_sym_db.RegisterMessage(Dictionary)
_sym_db.RegisterMessage(Dictionary.PairsEntry)


_DICTIONARY_PAIRSENTRY._options = None

_TWITTERANOMALYDETECTION = _descriptor.ServiceDescriptor(
  name='TwitterAnomalyDetection',
  full_name='twitteranomalydetection.TwitterAnomalyDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=243,
  serialized_end=360,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectAnomalies',
    full_name='twitteranomalydetection.TwitterAnomalyDetection.DetectAnomalies',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_DICTIONARY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERANOMALYDETECTION)

DESCRIPTOR.services_by_name['TwitterAnomalyDetection'] = _TWITTERANOMALYDETECTION

# @@protoc_insertion_point(module_scope)
