# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: anomaly_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='anomaly_detection.proto',
  package='twitteranomalydetection',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x61nomaly_detection.proto\x12\x17twitteranomalydetection\"B\n\x07Request\x12\x10\n\x08raw_json\x18\x01 \x01(\t\x12\x11\n\tonly_last\x18\x02 \x01(\t\x12\x12\n\nresampling\x18\x03 \x01(\x08\"\x1b\n\x08Response\x12\x0f\n\x07\x65ntries\x18\x01 \x03(\x02\x32s\n\x17TwitterAnomalyDetection\x12X\n\x0f\x44\x65tectAnomalies\x12 .twitteranomalydetection.Request\x1a!.twitteranomalydetection.Response\"\x00\x62\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='twitteranomalydetection.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_json', full_name='twitteranomalydetection.Request.raw_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='only_last', full_name='twitteranomalydetection.Request.only_last', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='resampling', full_name='twitteranomalydetection.Request.resampling', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=118,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='twitteranomalydetection.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='twitteranomalydetection.Response.entries', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'anomaly_detection_pb2'
  # @@protoc_insertion_point(class_scope:twitteranomalydetection.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'anomaly_detection_pb2'
  # @@protoc_insertion_point(class_scope:twitteranomalydetection.Response)
  })
_sym_db.RegisterMessage(Response)



_TWITTERANOMALYDETECTION = _descriptor.ServiceDescriptor(
  name='TwitterAnomalyDetection',
  full_name='twitteranomalydetection.TwitterAnomalyDetection',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=149,
  serialized_end=264,
  methods=[
  _descriptor.MethodDescriptor(
    name='DetectAnomalies',
    full_name='twitteranomalydetection.TwitterAnomalyDetection.DetectAnomalies',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TWITTERANOMALYDETECTION)

DESCRIPTOR.services_by_name['TwitterAnomalyDetection'] = _TWITTERANOMALYDETECTION

# @@protoc_insertion_point(module_scope)
