apiVersion: v1
kind: Pod
metadata:
  name: grpc-client
spec:
  containers:
    - name: grpc-client
      image: cmdaa/grpc-client:0.1
      command: ['sh', '-c', "exec tail -f /dev/null"]
      env:
        - name: ANOMALY_DETECTION_HOST
          value: twitter-anomaly-detection 
